### ISSUE TITLE
PyInstaller Error

### ISSUE THREAD

**Issue by pouyamiralayi** [realgam3/pymultitor#16]
Hello there!
First, i must appreciate the work you have done here, it is amazing.
Second, is it possible to produce binary from this package using pyinstaller?
I did this: `pyinstaller pymultitor.py` and it goes OK; but when i run the executable it on my windows 7 x64 machine, the result is:
`Traceback (most recent call last):
  File "pymultitor.py", line 33, in <module>
  File "c:\users\sadra\appdata\local\temp\pip-install-iuvvcz\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\mitmproxy\flow\__init__.py", line 5, in <module>
  File "c:\users\sadra\appdata\local\temp\pip-install-iuvvcz\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\mitmproxy\flow\master.py", line 15, in <module>
  File "c:\users\sadra\appdata\local\temp\pip-install-iuvvcz\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\mitmproxy\onboarding\app.py", line 12, in <module>
  File "site-packages\netlib\utils.py", line 75, in path
ValueError: dataPath: C:\Users\SADRA\AppData\Local\Temp\_MEI57~1\mitmproxy\onboarding/templates does not exist.
[6124] Failed to execute script pymultitor
`
I went through the release section of mitm proxy and back in there i saw some hooks provided for the pyinstaller: https://github.com/mitmproxy/mitmproxy/tree/master/release/hooks
i used these hooks along with pyinstaller:
`pyinstaller --additional-hooks-dir=. pymultitor.py
`
and the process failed with this error:
`Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named windivert_dll
Traceback (most recent call last):
  File "d:\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "d:\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Anaconda2\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "d:\anaconda2\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "d:\anaconda2\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "d:\anaconda2\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "d:\anaconda2\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "d:\anaconda2\lib\site-packages\PyInstaller\building\build_main.py", line 213, in __init__
    self.__postinit__()
  File "d:\anaconda2\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "d:\anaconda2\lib\site-packages\PyInstaller\building\build_main.py", line 472, in assemble
    module_hook.post_graph()
  File "d:\anaconda2\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "d:\anaconda2\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "d:\anaconda2\lib\site-packages\PyInstaller\hooks\hook-pydivert.py", line 3, in <module>
    datas = collect_data_files('pydivert.windivert_dll')
  File "d:\anaconda2\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 720, in collect_data_files
    pkg_base, pkg_dir = get_package_paths(package)
  File "d:\anaconda2\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 530, in get_package_paths
    file_attr = get_module_file_attribute(package)
  File "d:\anaconda2\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 336, in get_module_file_attribute
    raise ImportError
ImportError
`
Have you tried building binary out of pymultitor?
in case you did, i will appreciate sharing the experience, especially for windows machine.
Thanks in advance.

**Comment by pouyamiralayi** [comment]
Hi again! :+1: 
the above error was because of inconsistency between the version of mitmproxy required and the one i had installed. i fixed the problem, now the build goes fine with pyinstaller, but the issue is that when i run the script using python 3.6, it will output this error:
`    from mitmproxy.flow import State, FlowMaster as Master
ImportError: cannot import name 'State'
`
Thanks in advance.
