### ISSUE TITLE
[bug] does not fail safe and proxies request, leaking real ip

### ISSUE THREAD

**Issue by superuser5** [realgam3/pymultitor#22]
Hello,
This may be a repeat of the previous bug that I have filed, but I have installed pymultitor on the macOS Mojave 10.14.6 using "pip3 install pymultitor", installed tor with brew and get the following error during the start of the pymultitor and traffic is not tunneling through tor (getting real ip when querying https://ipinfo.io/ip):

Installation:
```
python3 -V
Python 3.7.6
pip3 install pymultitor
pymultitor -v
pymultitor 3.1.0
brew install tor
==> Pouring tor-0.4.2.6.mojave.bottle.tar.gz
```

Burp proxy sending GET request to https://ipinfo.io/ip and reply with a real address.

Error and log that request been handled by the pymultitor:
```
pymultitor -p 20 --on-count 1 --on-rst -lp 8085
Loading script /usr/local/lib/python3.7/site-packages/pymultitor.py
Addon error: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/addonmanager.py", line 42, in safecall
    yield
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/addons/script.py", line 102, in loadscript
    ctx.master.addons.register(ns)
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/addonmanager.py", line 162, in register
    self.master.options.process_deferred()
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 326, in process_deferred
    self.update(**update)
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 225, in update
    u = self.update_known(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 216, in update_known
    self._options[k].set(v)
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/optmanager.py", line 57, in set
    typecheck.check_option_type(self.name, value, self.typespec)
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/utils/typecheck.py", line 74, in check_option_type
    raise e
TypeError: Expected <class 'bool'> for on_rst, but got <class 'NoneType'>.

Proxy server listening at http://127.0.0.1:8085
127.0.0.1:52064: clientconnect
127.0.0.1:52064: GET https://ipinfo.io/ip
              << 200 OK 15b
127.0.0.1:52064: clientdisconnect
```

**Comment by realgam3** [comment]
In the next version it will not leak the IP address.
