### ISSUE TITLE
ImportError: cannot import name 'HTTPResponse' from 'mitmproxy.http' (C:\lib\site-packages\mitmproxy\http.py)

### ISSUE THREAD

**Issue by klaksik** [realgam3/pymultitor#33]
hi gyse, i`m have problem:
Traceback (most recent call last):
  File "C:\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Scripts\pymultitor.exe\__main__.py", line 4, in <module>
  File "C:\lib\site-packages\pymultitor.py", line 14, in <module>
    from mitmproxy.http import HTTPResponse
ImportError: cannot import name 'HTTPResponse' from 'mitmproxy.http' (C:\lib\site-packages\mitmproxy\http.py)

**Comment by BerendJansen21** [comment]
I am having the same issue. Any help would be appreciated.... I get the following when calling on pymultitor:

└─$ pymultitor --help                               
Traceback (most recent call last):
  File "/usr/local/bin/pymultitor", line 33, in <module>
    sys.exit(load_entry_point('PyMultitor==3.2.0', 'console_scripts', 'pymultitor')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/pymultitor", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/PyMultitor-3.2.0-py3.11.egg/pymultitor.py", line 15, in <module>
    from mitmproxy.http import HTTPResponse
ImportError: cannot import name 'HTTPResponse' from 'mitmproxy.http' (/usr/lib/python3/dist-packages/mitmproxy/http.py)

**Comment by realgam3** [comment]
It looks like mitmproxy changed their code, you have a dev branch with a
higher version. you can check it out or you can use the docker for now…

**Comment by BerendJansen21** [comment]
Thanks that's what I figured. I tried to install an older version of mitmproxy but then got another issue with a dependency when installing that...

I am now look into 'IP rotate' as an extension of Burp Suite Pro. I seem to have found a working version of Pro.

Docker I haven't heard of (I'm fairly new to Linux..). Can you let me know what it is?

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
